format = " $directory$git_branch$git_status$nodejs$golang $character"
add_newline = false

[directory]
truncation_length = 2
style = "bold #BD93F9"          # purple

[git_branch]
symbol = " "
style = "bold #FF79C6"          # pink

[git_status]
style = "bold #FF5555"          # red
ahead = "⇡${count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"

[nodejs]
symbol = " "
style = "bold #50FA7B"          # green

[golang]
symbol = " "
style = "bold #8BE9FD"          # cyan

[python]
symbol = " "
style = "bold #F1FA8C"          # yellow

[character]
success_symbol = "[❯](bold #50FA7B)"   # green
error_symbol = "[❯](bold #FF5555)"     # red
